version: '3.8'
<<<<<<< HEAD
services:
  db:
    image: mysql:8.0
    container_name: db_aerolinea
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_aerolinea
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    image: openjdk:17
    container_name: spring_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_aerolinea
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_NAME: donbosco
      SERVER_PORT: 8080
      LOGGING_FILE_NAME: logs/spring-boot-app.log
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
=======

services:
  springboot-app:
    build: .
    container_name: donbosco-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/db_aerolinea
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
>>>>>>> fbd44d2a69fa6e40a71fe426bb546c2164f277a7
